server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

#日志
logging:
  config: classpath:log/logback.xml

spring:
  #激活哪一个环境的配置文件
  profiles:
    active: test
  application:
    name: p2s
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #网络请求配置
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  #视图配置
  mvc:
    view:
      prefix: /templates/
      suffix: .*
    throw-exception-if-no-handler-found: true
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    name: p2sDB
    driver-class-name: org.sqlite.JDBC
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 5
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 15
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 连接池母子
      pool-name: HikariCP
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
  jpa:
    #设置数据库为sqlite
    database-platform: com.example.common.sqlite.SQLiteDialect
    #显示执行的语句（开了能在日志看到jpa执行的sql语句）
    show-sql: true
    #自行百度，不累述
    hibernate:
      ddl-auto: update
    open-in-view: true






