
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

#日志
logging:
  config: classpath:log/logback.xml

spring:
  #激活哪一个环境的配置文件
  profiles:
    active: test
  application:
    name: dataAdmin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #网络请求配置
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  #视图配置
  mvc:
    view:
      prefix: /templates/
      suffix: .*
    throw-exception-if-no-handler-found: true
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 5
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 15
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 连接池母子
      pool-name: HikariCP
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
  redis:
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

#mybatis
mybatis-plus:
  mapperLocations: classpath*:mapper/**/*.xml
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射
    #    mapUnderscoreToCamelCase: true
    callSettersOnNulls: true
    #是否展示sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  GlobalConfig:
    DbConfig:
      idType: AUTO
      capitalMode: true
      #逻辑删除配置
      logicDeleteValue: 0
      logicNotDeleteValue: 1

asyncExecutor:
  corePoolSize: 100
  maxPoolSize: 200
  queueCapacity: 10000

startSms: fasle

# token有效期，单位秒
jwtTimeOut: 3600




