server:
  port: 13146

spring:
  datasource:
    url: jdbc:mysql://10.120.0.42:3306/basicdataservice?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0


nacos:
  host: 172.18.18.127:8848

hbase:
  url: 172.18.18.180
  prot: 2181
  parent: /hbase
  maxsize: 1048576000

fluentd:
  #是否上传日志至日志系统
  isRun: false
  #fluentd地址
  remoteHost: 172.18.18.154
  #fluentd接收日志端口
  port: 24224
  #fluentd转发标签
  tag: elasticsearch
  props:
    serverName: data_admin管理服务